import os

Import('env')

contents = []
content = 'overlay.js overlay.xul sidebar.js sidebar.xul'
for c in content.split(' '):
    contents.append(os.path.join('chrome', 'content', c))

skin = 'chmfox_16.png chmfox_24.png overlay.css'
for s in skin.split(' '):
    contents.append(os.path.join('chrome', 'skin', s))

Return('contents')
